---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[test]
  - name: ubuntu-12.04
    run_list:
      - recipe[test]
  - name: ubuntu-14.04
    run_list:
      - recipe[test]
  - name: debian-7.6
    run_list:
      - recipe[test]
  - name: centos-6.5
  - name: centos-7.0
  - name: centos-5.10
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[ruby::default]
    attributes:
